"""
LightUI Python Binding Type Stubs

提供 IDE 自动补全和类型检查支持。
"""

from typing import Any, Callable, Dict, List, Optional, Tuple, Union, overload

# 类型别名
JsonValue = Union[None, bool, int, float, str, List[Any], Dict[str, Any]]
WatchCallback = Callable[[JsonValue], None]
HostCallback = Callable[[JsonValue], JsonValue]
ResizeCallback = Callable[[int, int], None]
CloseCallback = Callable[[], None]
FocusCallback = Callable[[], None]
UpdateCallback = Callable[[float], None]
RenderCallback = Callable[[], None]
IdleCallback = Callable[[], None]

def version() -> str:
    """获取 LightUI 版本号"""
    ...

def cleanup_dom_bindings(runtime: "Runtime") -> None:
    """清理 DOM 绑定和绑定映射（在销毁运行时之前调用）"""
    ...

def clear_font_cache() -> None:
    """清理字体缓存"""
    ...

def set_image_base_path(path: str) -> None:
    """设置图片加载的基础路径"""
    ...


# ========== State 类 ==========

class State:
    """状态基类"""

    @property
    def name(self) -> str:
        """状态名称"""
        ...

    def get(self) -> JsonValue:
        """获取状态值"""
        ...

    def set(self, value: JsonValue) -> None:
        """设置状态值"""
        ...

    def watch(self, callback: WatchCallback) -> int:
        """监听状态变化，返回 watch_id"""
        ...

    def unwatch(self, watch_id: int) -> None:
        """取消监听"""
        ...


class IntState(State):
    """整数状态，支持原子操作"""

    def get(self) -> int: ...
    def set(self, value: int) -> None: ...
    def increment(self, delta: int = 1) -> None:
        """原子增加"""
        ...
    def multiply(self, factor: float) -> None:
        """原子乘法"""
        ...


class StringState(State):
    """字符串状态，支持字符串操作"""

    def get(self) -> str: ...
    def set(self, value: str) -> None: ...
    def append(self, suffix: str) -> None:
        """追加文本"""
        ...
    def prepend(self, prefix: str) -> None:
        """前置文本"""
        ...
    def __len__(self) -> int: ...


class ListState(State):
    """列表状态，支持数组操作"""

    def get(self) -> List[Any]: ...
    def append(self, item: JsonValue) -> None:
        """添加元素到末尾"""
        ...
    def pop(self) -> None:
        """移除最后一个元素"""
        ...
    def shift(self) -> None:
        """移除并返回第一个元素"""
        ...
    def unshift(self, item: JsonValue) -> None:
        """添加元素到开头"""
        ...
    def remove(self, index: int) -> None:
        """移除指定位置的元素"""
        ...
    def clear(self) -> None:
        """清空列表"""
        ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> JsonValue: ...
    def __setitem__(self, index: int, value: JsonValue) -> None: ...


class DictState(State):
    """字典状态，支持对象操作"""

    def get(self) -> Dict[str, Any]: ...
    def set_key(self, key: str, value: JsonValue) -> None:
        """设置键值"""
        ...
    def remove_key(self, key: str) -> None:
        """移除键"""
        ...
    def clear(self) -> None:
        """清空字典"""
        ...
    def keys(self) -> List[str]:
        """获取所有键"""
        ...
    def __getitem__(self, key: str) -> JsonValue: ...
    def __setitem__(self, key: str, value: JsonValue) -> None: ...
    def __contains__(self, key: str) -> bool: ...


# ========== App 与 BatchContext ==========

class App:
    """LightUI 应用主类"""

    def __init__(
        self,
        title: str = "LightUI App",
        width: int = 800,
        height: int = 600,
    ) -> None: ...

    def state(
        self, name: str, initial: JsonValue = None
    ) -> Union[State, IntState, StringState, ListState, DictState]:
        """创建或获取状态（根据 initial 类型自动推断子类）"""
        ...

    def bind(self, name: str, func: Callable[..., Any]) -> None:
        """绑定 Python 函数供 JS 调用"""
        ...

    def unbind(self, name: str) -> None:
        """解绑函数"""
        ...

    def load_file(self, path: str) -> None: ...
    def load_js(self, code: str) -> None: ...
    def run(self) -> None: ...
    def stop(self) -> None: ...
    def batch_begin(self) -> None:
        """进入批量模式"""
        ...
    def batch_end(self) -> None:
        """退出批量模式"""
        ...
    def process_queue(self) -> None:
        """处理队列（测试用）"""
        ...
    def __enter__(self) -> "App": ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...


class BatchContext:
    """批量操作上下文管理器"""

    def __init__(self, app: App) -> None: ...
    def __enter__(self) -> "BatchContext": ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...


# ========== TaskScheduler ==========

class TaskScheduler:
    """任务调度器，支持 setTimeout/setInterval 等 JS 定时器"""

    def __init__(self) -> None: ...


# ========== Element ==========

class Element:
    """DOM 元素"""

    @property
    def tag_name(self) -> str: ...

    @property
    def id(self) -> str: ...
    @id.setter
    def id(self, value: str) -> None: ...

    @property
    def class_name(self) -> str: ...
    @class_name.setter
    def class_name(self, value: str) -> None: ...

    @property
    def inner_html(self) -> str: ...
    @inner_html.setter
    def inner_html(self, value: str) -> None: ...

    @property
    def text_content(self) -> str: ...
    @text_content.setter
    def text_content(self, value: str) -> None: ...

    def get_attribute(self, name: str) -> str: ...
    def set_attribute(self, name: str, value: str) -> None: ...
    def remove_attribute(self, name: str) -> None: ...
    def query_selector(self, selector: str) -> Optional["Element"]: ...
    def query_selector_all(self, selector: str) -> List["Element"]: ...
    def is_valid(self) -> bool: ...


# ========== Document ==========

class Document:
    """DOM 文档"""

    @property
    def body(self) -> Optional[Element]: ...

    def create_element(self, tag_name: str) -> Optional[Element]: ...
    def query_selector(self, selector: str) -> Optional[Element]: ...
    def query_selector_all(self, selector: str) -> List[Element]: ...
    def get_element_by_id(self, id: str) -> Optional[Element]: ...
    def load_html(self, html: str) -> bool:
        """加载 HTML 字符串"""
        ...
    def load_html_file(self, path: str) -> bool:
        """加载 HTML 文件"""
        ...
    def save_html(self) -> str:
        """保存为 HTML 字符串"""
        ...
    def set_base_path(self, path: str) -> None:
        """设置基础路径（用于解析相对 URL）"""
        ...
    def load_external_stylesheets(self) -> None:
        """加载文档中引用的外部样式表"""
        ...
    def execute_scripts(self) -> None:
        """执行文档中所有 script 标签"""
        ...
    def is_valid(self) -> bool: ...


# ========== Window ==========

class Window:
    """原生窗口"""

    def __init__(
        self,
        title: str = "LightUI Window",
        width: int = 800,
        height: int = 600,
        headless: bool = False,
        borderless: bool = False,
        transparent: bool = False,
        always_on_top: bool = False,
        resizable: bool = True,
        resize_border_width: int = 8,
    ) -> None: ...

    @property
    def title(self) -> str: ...
    @title.setter
    def title(self, value: str) -> None: ...

    @property
    def size(self) -> Tuple[int, int]: ...

    @property
    def position(self) -> Tuple[int, int]: ...

    @property
    def document(self) -> Optional[Document]: ...

    @property
    def is_borderless(self) -> bool:
        """是否无边框窗口"""
        ...

    @property
    def is_transparent(self) -> bool:
        """是否透明窗口"""
        ...

    @property
    def resize_border_width(self) -> int:
        """无边框窗口的调整大小边缘宽度"""
        ...

    @property
    def min_size(self) -> Tuple[int, int]:
        """窗口最小尺寸 (width, height)"""
        ...

    @property
    def max_size(self) -> Tuple[int, int]:
        """窗口最大尺寸 (width, height)"""
        ...

    def show(self) -> None: ...
    def hide(self) -> None: ...
    def close(self) -> None: ...
    def set_size(self, width: int, height: int) -> None: ...
    def set_position(self, x: int, y: int) -> None: ...
    def set_fullscreen(self, fullscreen: bool) -> None: ...
    def set_resizable(self, resizable: bool) -> None: ...
    def set_borderless(self, borderless: bool) -> None: ...
    def set_always_on_top(self, on_top: bool) -> None: ...
    def set_min_size(self, width: int, height: int) -> None:
        """设置窗口最小尺寸（0 表示不限制）"""
        ...
    def set_max_size(self, width: int, height: int) -> None:
        """设置窗口最大尺寸（0 表示不限制）"""
        ...
    def minimize(self) -> None: ...
    def maximize(self) -> None: ...
    def restore(self) -> None: ...
    def should_close(self) -> bool: ...
    def render(self) -> None: ...
    def swap_buffers(self) -> None: ...
    def needs_repaint(self) -> bool:
        """检查窗口是否需要重绘（增量渲染）"""
        ...
    def mark_dirty(self) -> None:
        """标记窗口需要重绘"""
        ...
    def set_js_runtime(self, runtime: "Runtime") -> None:
        """设置 JS 运行时到窗口的 Document"""
        ...
    def get_task_scheduler(self) -> TaskScheduler:
        """获取 TaskScheduler（用于 EventLoop 集成）"""
        ...
    def set_on_resize(self, callback: ResizeCallback) -> None: ...
    def set_on_close(self, callback: CloseCallback) -> None: ...
    def set_on_focus(self, callback: FocusCallback) -> None: ...
    def set_on_blur(self, callback: FocusCallback) -> None: ...
    def is_valid(self) -> bool: ...


# ========== EventLoop ==========

class EventLoop:
    """事件循环"""

    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, task_scheduler: TaskScheduler) -> None: ...

    def run(self) -> None:
        """运行事件循环（阻塞）"""
        ...
    def stop(self) -> None:
        """停止事件循环"""
        ...
    def run_once(self) -> None:
        """运行一次事件循环迭代"""
        ...
    def is_running(self) -> bool: ...
    def should_quit(self) -> bool: ...
    def set_quickjs_runtime(self, runtime: "Runtime") -> None:
        """设置 QuickJS 运行时（用于执行 JS 定时器回调和全局 EventLoop）"""
        ...
    def set_window(self, window: Window) -> None:
        """设置 Window（用于自动增量渲染）"""
        ...
    def set_state_manager(self, app: App) -> None:
        """设置 StateManager（用于线程安全的状态队列处理，每帧自动调用）"""
        ...
    def set_update_callback(self, callback: UpdateCallback) -> None: ...
    def set_render_callback(self, callback: RenderCallback) -> None: ...
    def set_idle_callback(self, callback: IdleCallback) -> None: ...


# ========== Runtime ==========

class Runtime:
    """QuickJS JavaScript 运行时"""

    def __init__(self) -> None: ...

    def eval(self, code: str, filename: str = "<eval>") -> JsonValue:
        """执行 JavaScript 代码"""
        ...
    def eval_module(self, code: str, filename: str = "<module>") -> JsonValue:
        """执行 ES6 模块代码"""
        ...
    def eval_file(self, path: str) -> JsonValue:
        """执行 JavaScript 文件"""
        ...
    def register_module(self, name: str, code: str) -> None:
        """注册虚拟 ES 模块（如 'preact', 'preact/hooks'）"""
        ...
    def set_base_module_path(self, path: str) -> None:
        """设置模块基础路径（用于解析相对路径的模块导入）"""
        ...
    def init_fetch_bindings(self, task_scheduler: TaskScheduler) -> None:
        """初始化 fetch API（网络请求）"""
        ...


# ========== HostBridge ==========

class HostBridge:
    """Python ↔ JS 通信桥接类"""

    def __init__(self, runtime: Runtime, app: App) -> None: ...

    def bind(self, name: str, func: HostCallback) -> None:
        """绑定 Python 函数供 JS 调用"""
        ...
    def unbind(self, name: str) -> None:
        """解绑 Python 函数"""
        ...
    def call(self, name: str, args: JsonValue = None) -> JsonValue:
        """调用已注册的函数"""
        ...
    def is_valid(self) -> bool:
        """检查桥接是否已正确初始化"""
        ...


# ========== DevToolsManager ==========

class DevToolsManager:
    """开发者工具管理器（单例）"""

    @staticmethod
    def get_instance() -> "DevToolsManager":
        """获取单例实例"""
        ...
    def initialize(self, document: Document, window: Window) -> None:
        """初始化 DevTools"""
        ...
    def open(self) -> None:
        """打开 DevTools 面板"""
        ...
    def close(self) -> None:
        """关闭 DevTools 面板"""
        ...
    def toggle(self) -> None:
        """切换 DevTools 显示状态"""
        ...
    def is_open(self) -> bool:
        """检查 DevTools 是否打开"""
        ...
    def shutdown(self) -> None:
        """关闭 DevTools"""
        ...
